### ISSUE TITLE
Add support for Molpro format

### ISSUE THREAD

**Issue by mlestep** [jevandezande/qgrep#3]
Support for the Molpro basis set format would be really nice. I'm hoping to submit a pull request from my fork with an implementation of this feature.

**Comment by jevandezande** [comment]
I can currently read a Molpro formatted basis set, I never got around to coding the writer.
I don't see any forks of this on Github. If you push your preliminary work, I can comment on it if you get stuck (the Molpro format is ugly).
Also, don't forget to write a test (put in `basisset_unittest.py`, mirroring the tests for other formats).

**Comment by mlestep** [comment]
Sounds great!
Hmm, you're right, my fork isn't showing up here. I can see it (https://github.com/mlestep/qgrep) and it indicates that it's forked from your repository and is public, so I'm not sure what the issue is.
Good reminder, I'll make sure to put in a test.

**Comment by jevandezande** [comment]
You haven't pushed any commits, so your fork won't show up.
